"""Your awesome package.

A modern Python project template with best practices and modern tooling.

This package demonstrates:

- Modern project structure with Pixi and pyproject.toml
- Automated version management with hatch-vcs
- Type hints with MyPy
- Code formatting with Ruff
- Testing with pytest and coverage
- Automated API documentation with mkdocstrings
- Comprehensive GitHub Actions CI/CD
- CLI interface with Typer

Attributes:
    __title__: The title of the package
    __description__: A short description of the package
    __author__: The author of the package
    __license__: The license type
    __version__: The version of the package (auto-generated by hatch-vcs)

Example:
    Import the package:

    >>> import your_package_name
    >>> print(your_package_name.__version__)
    0.0.0+unknown

    Use the CLI:

    >>> from your_package_name.cli import main
    >>> main()
"""

try:
    from .._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__title__ = "your-package-name"
__description__ = "A modern Python project with best practices"
__author__ = "Your Name"
__license__ = "MIT"

__all__ = ["__version__"]
